### ISSUE TITLE
Auto-magically determine version number

### ISSUE THREAD

**Issue by mrbiggred** [corgibytes/freshli#228]
Use [GitVersion](https://github.com/GitTools/GitVersion) to generate the version number for this project.  Actually the plan is to use the [GitHub Action](https://github.com/marketplace/actions/gittools).  GitVersion will be setup to support the Cactus Branching model (see below for details) which requires a setup like:

```
# GitVersion.yml
branches:
  master:
    mode: ContinuousDeployment
    tag: 'alpha'
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
  release:
    tag: 'beta'
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
```

The idea is that only `release-X.Y` branches are tagged something like `vX.Y.Z`.  Then this tag is merged back to `main` GitVersion will calculate the next version number as `vX.Y+1.0.0`.

When a feature branch is merged to `release-X.Y` for a bug fix only the patch number will be incremented and the major, minor, and patch numbers left as is.

GitVersion generates several different version number formats such as:

- AssemblySemVer: 0.8.0.0
- NuGetVersionV2: 0.8.0-alpha0001
- MajorMinorPatch: 0.8.0

GitVersion can set the version in C# Assembly Version files now that they have fixed this [issue](https://github.com/GitTools/actions/issues/125).

----

An example of the Cactus or Trident Branching model:

![Proposed CB Git Branches](https://user-images.githubusercontent.com/17273852/107102929-21595980-67d9-11eb-876d-624cab9e0103.png)
