### ISSUE TITLE
Auto generate change log and GitHub releases

### ISSUE THREAD

**Issue by mrbiggred** [corgibytes/freshli#241]
If possible it would nice we would auto generate the change log and GitHub releases.  My first thought on a tool to do this is [GitReleaseManager](https://github.com/GitTools/GitReleaseManager) which is made by the same people who made [GitVersion](https://github.com/GitTools/GitVersion) (#228).

GitReleaseManager works by having creating a milestone with version number (e.g. [v0.3.0](https://github.com/corgibytes/freshli/milestone/4) and assigning issues to that milestone.  Then in the CI we run the GitReleaseMangaer to generate both the GitHub Release and the change log.

I tested this in another project and it seemed to work pretty well.  An example of the GitHub action file is:

```yml
# Assume we have the next version number via GitVersion.

- uses: gittools/actions/gitreleasemanager/setup@v0.9.8
name: Install GitReleaseManager
with:
  versionSpec: '0.11.0'

- uses: gittools/actions/gitreleasemanager/create@v0.9.8
name: Create GitHub Release for ${{ steps.gitversion.outputs.majorMinorPatch }}  if it Does not Exist
continue-on-error: true
with:
  token: ${{ secrets.GITHUB_TOKEN }}
  owner: 'repo-owner'
  repository: 'my-repo'
  milestone: 'v${{ steps.gitversion.outputs.majorMinorPatch }}' 

# This will generate the change log for all the GitHub Releases.
- name: Generate Change Log (no GitHub Action)
run: |
  dotnet-gitreleasemanager export --token ${{ secrets.GITHUB_TOKEN }} -o 'repo-owner' -r 'my-repo' -f 'CHANGELOG.md'
  cat CHANGELOG.md

- uses: stefanzweifel/git-auto-commit-action@v4
name: Commit Change Log if it Changed
with:
  commit_message: Committing auto generated change log.
  file_pattern: CHANGELOG.md
```

Because the above commits the change log file, if it changed, we need to make sure we don't create a infinite loop of CI builds.
